name: Pintos CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull loeper/stanford-cs212-pintos:latest

    - name: Run Pintos test
      continue-on-error: true
      run: |
        docker run --name pintos --workdir /pintos/src/threads \
          --entrypoint '/bin/bash' -v ${{ github.workspace }}:/pintos \
          loeper/stanford-cs212-pintos:latest -c "make && make check --ignore-errors"

    - name: Get test results
      run: |
        docker cp  pintos:/pintos/src/threads/build/results $PWD
        {
          echo 'TEST_RESULT<<EOF'
          cat $PWD/results
          echo EOF
        } >> "$GITHUB_ENV"
        

    - name: Find Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: "pass"

    - name: Create comment
      if: steps.fc.outputs.comment-id == ''
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body:
        reactions: rocket

    - name: Create or update comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          Test output
          ${{ env.TEST_RESULT }}
        edit-mode: replace