name: Pintos CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Pintos test
      uses: addnab/docker-run-action@v3
      with:
        image: loeper/stanford-cs212-pintos:latest
        options: -v ${{ github.workspace }}/pintos:/pintos --workdir /pintos/src/threads
        entrypoint: "/bin/bash"
        run: |
          echo $PWD
          ls
          make
          make check

    - name: Get test results
      run: echo "RESULTS=$(cat ./pintos/src/threads/build/results)" >> $GITHUB_ENV

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ```
          ${{ env.RESULTS }}
          ```
        edit-mode: replace
