name: Pintos CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull loeper/stanford-cs212-pintos:latest

    - name: Run Pintos test
      continue-on-error: true
      run: |
        docker run --name pintos --workdir /pintos/src/threads \
          --entrypoint '/bin/bash' -v ${{ github.workspace }}:/pintos \
          loeper/stanford-cs212-pintos:latest -c "make && make check --ignore-errors"

    - name: Get test results
      run: |
        docker cp  pintos:/pintos/src/threads/build/results $PWD
        echo "RESULTS=$(cat $PWD/results)" >> $GITHUB_ENV

    - name: Comment PR
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          ```
          ${{ env.RESULTS }}
          ```
        edit-mode: replace
