name: Pintos CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull Docker Image
      run: docker pull loeper/stanford-cs212-pintos:latest

    - name: Run Pintos test
      continue-on-error: true
      run: |
        docker run --name pintos --workdir /pintos/src/userprog \
          --entrypoint '/bin/bash' -v ${{ github.workspace }}:/pintos \
          loeper/stanford-cs212-pintos:latest -c "make && make check --ignore-errors"

    - name: Get test results
      run: |
        docker cp  pintos:/pintos/src/userprog/build/results $PWD
        {
          echo 'TEST_RESULT<<EOF'
          cat $PWD/results
          echo EOF
        } >> "$GITHUB_ENV"
        
    - name: Process Test Results
      run: |
        chmod +x ${{ github.workspace }}/helper/test-results-conversion.sh
        ${{ github.workspace }}/helper/test-results-conversion.sh

    - name: Find Comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        body-includes: "Test Results"

    - name: Create or update comment
      if: github.event_name == 'pull_request'
      uses: peter-evans/create-or-update-comment@v3
      with:
        comment-id: ${{ steps.fc.outputs.comment-id }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: "test_results.md"
        edit-mode: replace